pipelines:
   default:
     - step:
        script:
            - export IMAGE_NAME=gabinetedigital/gdos:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME -f ObjectServer.API/Dockerfile .
            - docker login --username $DOCKER_USER --password $DOCKER_PASS
            - docker push $IMAGE_NAME
options:
    docker: true